# fly.toml app configuration file generated for ts-admin-panel on 2025-08-22T19:40:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ts-admin-panel'
primary_region = 'fra'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
